import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { splashStyles } from "./src/constants/splash";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
      </head>
      <body>
        <div id={"globalLoader"}>
          <span className="loader"></span>
        </div>
        {children}
      </body>
    </html>
  );
}
